### ISSUE TITLE
Change keyboard code to something a bit more reliable

### ISSUE THREAD

**Issue by gameblabla** [megatron-uk/pc98launcher#1]
Hello,
i ran this on my own Xe10 PC-9821 with my own PC-98 keyboard and i did notice that my keyboard doesn't work with some games like Doom and GTS RS.
It sort of works with pc98launcher but the issue is that after you press a couple of keys, it will eventually stop responding to further more key presses (similar to what i got in doom).

I was able to run my game (or at least my PC-9801 version of it) fine on that same keyboard.
I think tho, it would be a better idea to use BIOS routines for keyboard handling.

You can see an example here :
https://github.com/gameblabla/copyright_infringement_ports/blob/simp/PC9821/input/pc98/input.c

Also, unrelated but i made a simple win32 editor for pc98launcher here : https://github.com/gameblabla/pc98launcher_editor

**Comment by megatron-uk** [comment]
Thanks for the feedback. I do wonder if the reason I don't see the same behaviour is that I don't actually have an original PC-98 keyboard; I use a Classic PC Club PC98/PS2 adaptor for both mouse and keyboard.

I'll certainly take a look at changing the keyboard input routines - I'm (slowly) developing a 2D RPG engine, and PC-98 is one of the platforms I want it to run on, so incorporating the bios keyboard routines would sound like the sensible way forward.

**Comment by gameblabla** [comment]
Bought a new keyboard and it doesn't have the issue. It seems to be that this old keyboard in particular only works for older games for whatever reasons. I sold it anyway. No idea how to make it work on these either.
